version: "3.8"
services:
  express:
    image: aleksaed/weather
    ports:
      - 80:${PORT}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - PORT=${PORT}
    env_file: ".env"

  watchtower:
    image: containrrr/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
      -  WATCHTOWER_LABEL_ENABLE=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower