version: '3.8'

services: 
  front:
    build:
      context: ../ex-2.03/front/
      dockerfile: /home/aleksa/code/edu/helsinki/docker-mooc/part-2/ex-2.09/front.Dockerfile
      args:
        - REACT_APP_BACKEND_URL=/api/
    ports:
      - 5000

  back:
    build: ../ex-2.03/back/
    ports:
      - 8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
    depends_on:
      - db

  redis:
    image: redis

  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres #default for backend example app
    volumes:
      - ./database:/var/lib/postgresql/data

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - back
    restart: unless-stopped